### ISSUE TITLE
Cannot enter "between" range on axis

### ISSUE THREAD

**Issue by andig** [NatelEnergy/grafana-plotly-panel#49]
Both X- any Y axis allow specifying "Between" as range selection. However there's nowhere to enter the min/max values for between:

<img width="800" alt="screen shot 2018-10-02 at 13 09 32" src="https://user-images.githubusercontent.com/184815/46345334-76eb2d80-c644-11e8-8332-d757778ebf14.png">

I'm using v0.0.4.

**Comment by ryantxu** [comment]
I fixed this in 0.0.5... hopefully released soon :)

You can get it from master directly if you want

**Comment by andig** [comment]
Great, thank you! Waiting for grafana to publish...

**Comment by andig** [comment]
Same problem still. When selecting "between" no additional input fields are shown. Could you show how this is expected to look?

**Comment by andig** [comment]
@ryantxu as this is still a problem could you please reopen so it doesn't get lost?

**Comment by ryantxu** [comment]
sorry -- it is fixed in master, but 0.0.5 got released before this was included.  Still fixed, but needs to be released.

You can use the master branch though
